### ISSUE TITLE
アプリの起動方法が分からない

### ISSUE THREAD

**Issue by ba-hira** [nalgo-intern/teamC#55]
スクリプト(`*.py`)がトップディレクトリに複数あるうえに、READMEや仕様書に起動方法が記載されていないため、アプリを試そうとしたときにどうすればよいか迷ってしまう。

下記の対応をして欲しい。
- 不要なスクリプトを削除する
- 実験用スニペットを別のディレクトリに移す
- 起動方法をREADMEか仕様書、あるいはその両方に記載する

**Comment by UchidaArihito** [comment]
#57

**Comment by UchidaArihito** [comment]
Leave a comment
