### ISSUE TITLE
仕様書の図が表示されていない

### ISSUE THREAD

**Issue by ta-iwa** [nalgo-intern/teamC#60]
https://github.com/nalgo-intern/teamC/blob/master/doc/work.md

### 事象
図が表示されていない。

### 原因

ファイルがない。

### 修正方針

ファイルを正しい場所に置く。

### その他

図を表示する際は、`![図の名前](ファイルへの相対パス)`とするのが一般的。

**Comment by UchidaArihito** [comment]
#61
